In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [10]:
import glob
import os

all_files = glob.glob("Harga Bahan Pangan/train/*")
all_files

[]

In [9]:
all_df = pd.DataFrame({"Date": []})

for file in all_files:
    df = pd.read_csv(file)
    print(df)

            Date     Aceh     Bali   Banten  Bengkulu  DI Yogyakarta  \
0     2022-01-01      NaN      NaN      NaN       NaN            NaN
1     2022-01-02      NaN      NaN      NaN       NaN            NaN
2     2022-01-03      NaN      NaN      NaN       NaN            NaN
3     2022-01-04      NaN      NaN      NaN       NaN            NaN
4     2022-01-05      NaN      NaN      NaN       NaN            NaN
...          ...      ...      ...      ...       ...            ...
999   2024-09-26  15660.0  16210.0  14900.0   16100.0        16280.0
1000  2024-09-27  15720.0  16430.0  15950.0   16100.0        16300.0
1001  2024-09-28  15730.0  16510.0  15710.0   16100.0        15410.0
1002  2024-09-29  15610.0  16410.0  15680.0   16100.0        16280.0
1003  2024-09-30  15670.0  16340.0  15710.0   16100.0        16280.0

      DKI Jakarta  Gorontalo    Jambi  Jawa Barat  ...    Papua     Riau  \
0             NaN        NaN      NaN         NaN  ...      NaN      NaN
1             NaN        NaN      NaN         NaN  ...      NaN      NaN
2             NaN        NaN      NaN         NaN  ...      NaN      NaN
3             NaN        NaN      NaN         NaN  ...      NaN      NaN
4             NaN        NaN      NaN         NaN  ...      NaN      NaN
...           ...        ...      ...         ...  ...      ...      ...
999       16810.0    17460.0  15200.0     16800.0  ...  19150.0  16580.0
1000      16970.0    17520.0  15270.0     16820.0  ...  19150.0  16500.0
1001      16810.0    17720.0  15270.0     16810.0  ...  19150.0  16650.0
1002      16810.0    17660.0  15350.0     16750.0  ...  19150.0  16570.0
1003      16810.0    17770.0  15580.0     16830.0  ...  19150.0  16600.0

      Sulawesi Barat  Sulawesi Selatan  Sulawesi Tengah  Sulawesi Tenggara  \
0                NaN               NaN              NaN                NaN
1                NaN               NaN              NaN                NaN
2                NaN               NaN              NaN                NaN
3                NaN               NaN              NaN                NaN
4                NaN               NaN              NaN                NaN
...              ...               ...              ...                ...
999          15820.0           15980.0          17190.0            16620.0
1000         16070.0           15980.0          17170.0            17110.0
1001         15820.0           15980.0          17170.0            16600.0
1002         15820.0           16000.0          17170.0            16600.0
1003         16400.0           16030.0          17250.0            16790.0

      Sulawesi Utara  Sumatera Barat  Sumatera Selatan  Sumatera Utara
0                NaN             NaN               NaN             NaN
1                NaN             NaN               NaN             NaN
2                NaN             NaN               NaN             NaN
3                NaN             NaN               NaN             NaN
4                NaN             NaN               NaN             NaN
...              ...             ...               ...             ...
999          17150.0         15010.0           15720.0         16390.0
1000         17080.0         15090.0           15720.0         16320.0
1001         17040.0         14980.0           15740.0         16330.0
1002         17040.0         14940.0           15770.0         16160.0
1003         17080.0         15020.0           15780.0         16280.0

[1004 rows x 35 columns]
            Date     Aceh     Bali   Banten  Bengkulu  DI Yogyakarta  \
0     2022-01-01      NaN  76680.0  80020.0   43040.0        63490.0
1     2022-01-02      NaN  74370.0  81700.0   45830.0        64110.0
2     2022-01-03      NaN  72660.0  84630.0   53330.0        70680.0
3     2022-01-04      NaN  75000.0  88680.0   53840.0        69670.0
4     2022-01-05  50000.0  70020.0  79400.0   53840.0        63250.0
...          ...      ...      ...      ...       ...            ...
999   2024-09-26      NaN  36240.0  41050.0   45120.0        34040.0
1000  2024-09-27      NaN  35900.0  39740.0   46270.0        33880.0
1001  2024-09-28      NaN  35610.0  39440.0   46270.0        34240.0
1002  2024-09-29      NaN  34890.0  40140.0   45830.0        31180.0
1003  2024-09-30      NaN  33490.0  43160.0   45990.0        30420.0

      DKI Jakarta  Gorontalo    Jambi  Jawa Barat  ...     Papua     Riau  \
0         98730.0    64110.0  51740.0     91430.0  ...  105460.0  60000.0
1         98730.0    63440.0  59810.0     93530.0  ...  100990.0  60000.0
2         97420.0    67340.0  66470.0     86060.0  ...   96970.0  65000.0
3         95730.0    63990.0  65410.0     88960.0  ...   93580.0      NaN
4         88960.0    62670.0  64750.0     87970.0  ...   98180.0  65000.0
...           ...        ...      ...         ...  ...       ...      ...
999       45700.0    70720.0  45000.0     40810.0  ...   81980.0  57160.0
1000      45700.0    70200.0  44830.0     41740.0  ...   81400.0  57190.0
1001      44810.0    71450.0  44770.0     41050.0  ...   81400.0  56440.0
1002      44810.0    71700.0  43980.0     41080.0  ...   82130.0  58730.0
1003      44170.0    70400.0  44100.0     40760.0  ...   83050.0  56010.0

      Sulawesi Barat  Sulawesi Selatan  Sulawesi Tengah  Sulawesi Tenggara  \
0            72680.0           66000.0          84750.0            83440.0
1            67780.0           64250.0          82800.0            77920.0
2            68490.0           62610.0          61150.0            72530.0
3            64210.0           60620.0          78500.0            72470.0
4            65310.0           60440.0          75770.0            73930.0
...              ...               ...              ...                ...
999          41840.0           28040.0          53410.0            40170.0
1000         40930.0           27950.0          53830.0            39660.0
1001         42370.0           26380.0          51440.0            37480.0
1002         41540.0           26520.0          51120.0            36840.0
1003         41060.0           26140.0          51300.0            39870.0

      Sulawesi Utara  Sumatera Barat  Sumatera Selatan  Sumatera Utara
0            98580.0             NaN           68790.0         55000.0
1            90400.0             NaN           68220.0         68410.0
2            89100.0             NaN           71500.0         74700.0
3            79590.0             NaN           66170.0         70360.0
4            76580.0             NaN           66420.0         70360.0
...              ...             ...               ...             ...
999          77800.0         47690.0           42330.0         43800.0
1000         75390.0         49040.0           42240.0         44930.0
1001         76130.0         47200.0           42360.0         46900.0
1002         73840.0         51130.0           42190.0         43490.0
1003         74260.0         47400.0           42370.0         43610.0

[1004 rows x 35 columns]
            Date     Aceh     Bali   Banten  Bengkulu  DI Yogyakarta  \
0     2022-01-01  19400.0  19690.0  18820.0   18540.0        19580.0
1     2022-01-02  19100.0  19730.0  18660.0   18610.0        19580.0
2     2022-01-03  19220.0  19760.0  18640.0   18430.0        19580.0
3     2022-01-04  19160.0  19990.0  18850.0   18360.0        19580.0
4     2022-01-05  19570.0  19990.0  18980.0   18430.0        19480.0
...          ...      ...      ...      ...       ...            ...
999   2024-09-26  18070.0  17670.0  16870.0   17120.0        16310.0
1000  2024-09-27  18150.0  17750.0  17170.0   17150.0        16340.0
1001  2024-09-28  18080.0  17750.0  16970.0   17150.0        16380.0
1002  2024-09-29  18040.0  17750.0  16860.0   17150.0        16380.0
1003  2024-09-30  18000.0  17680.0  17260.0   17260.0        16380.0

      DKI Jakarta  Gorontalo    Jambi  Jawa Barat  ...    Papua     Riau  \
0         19750.0    19880.0  18300.0     19450.0  ...  18980.0  19540.0
1         19750.0    19940.0  18340.0     19460.0  ...  19970.0  19480.0
2         19830.0    19890.0  18360.0     19440.0  ...  19220.0  19480.0
3         19830.0    19890.0  18300.0     19400.0  ...  19290.0  19710.0
4         19830.0    19890.0  18190.0     19400.0  ...  19240.0  19690.0
...           ...        ...      ...         ...  ...      ...      ...
999       18170.0    19560.0  16550.0     17490.0  ...  19910.0  17290.0
1000      18080.0    19680.0  16530.0     17470.0  ...  19910.0  17280.0
1001      18080.0    19840.0  16650.0     17470.0  ...  19910.0  17340.0
1002      18080.0    19780.0  16650.0     17550.0  ...  19910.0  17420.0
1003      18280.0    19750.0  16650.0     17510.0  ...  19910.0  17250.0

      Sulawesi Barat  Sulawesi Selatan  Sulawesi Tengah  Sulawesi Tenggara  \
0            20940.0           18320.0          18520.0            19980.0
1            21110.0           18510.0          18600.0            19380.0
2            21110.0           18230.0          18790.0            20030.0
3            20460.0           18460.0          18540.0            19820.0
4            20540.0           18530.0          18610.0            20130.0
...              ...               ...              ...                ...
999          18920.0           17780.0          19340.0            20080.0
1000         18380.0           17780.0          19410.0            19990.0
1001         18920.0           17750.0          19280.0            19850.0
1002         18920.0           17800.0          19230.0            19880.0
1003         19250.0           17770.0          19280.0            20040.0

      Sulawesi Utara  Sumatera Barat  Sumatera Selatan  Sumatera Utara
0            22130.0         18230.0           18920.0         19440.0
1            21630.0         18340.0           18790.0         19370.0
2            21570.0         18370.0           18810.0         19200.0
3            21510.0         18460.0           18820.0         19180.0
4            21150.0         18470.0           18740.0         19170.0
...              ...             ...               ...             ...
999          17330.0         17740.0           17180.0         17850.0
1000         17090.0         17590.0           17180.0         18030.0
1001         17160.0         17830.0           17210.0         18200.0
1002         17100.0         17660.0           17260.0         17980.0
1003         17160.0         17730.0           17210.0         18100.0

[1004 rows x 35 columns]
            Date     Aceh     Bali   Banten  Bengkulu  DI Yogyakarta  \
0     2022-01-01  27440.0  22390.0  27240.0   25960.0        24940.0
1     2022-01-02  29070.0  22590.0  26430.0   26590.0        24940.0
2     2022-01-03  27970.0  22640.0  27550.0   27080.0        24360.0
3     2022-01-04  28140.0  22090.0  26600.0   26970.0        24360.0
4     2022-01-05  27590.0  22100.0  26470.0   27180.0        23740.0
...          ...      ...      ...      ...       ...            ...
999   2024-09-26  39350.0  35640.0  38150.0   39490.0        36620.0
1000  2024-09-27  39260.0  35640.0  38970.0   39500.0        36170.0
1001  2024-09-28  39240.0  35570.0  38320.0   39420.0        36170.0
1002  2024-09-29  39160.0  35600.0  37970.0   39100.0        36170.0
1003  2024-09-30  39110.0  35530.0  39250.0   39100.0        36090.0

      DKI Jakarta  Gorontalo    Jambi  Jawa Barat  ...    Papua     Riau  \
0         32770.0    30950.0  25130.0     27010.0  ...  41210.0  27460.0
1         29490.0    30800.0  25380.0     27000.0  ...  44050.0  27320.0
2         32180.0    31560.0  25740.0     27080.0  ...  41580.0  27360.0
3         32180.0    31920.0  25240.0     27360.0  ...  41290.0  27260.0
4         32180.0    32410.0  25220.0     27460.0  ...  39790.0  26530.0
...           ...        ...      ...         ...  ...      ...      ...
999       40000.0    43790.0  37470.0     38400.0  ...  51110.0  38000.0
1000      40600.0    45520.0  37470.0     38360.0  ...  51110.0  37880.0
1001      39300.0    43270.0  37480.0     38390.0  ...  51110.0  38030.0
1002      39120.0    43010.0  37480.0     38320.0  ...  51340.0  38110.0
1003      40520.0    44480.0  37430.0     38400.0  ...  51350.0  38290.0

      Sulawesi Barat  Sulawesi Selatan  Sulawesi Tengah  Sulawesi Tenggara  \
0            27950.0           27580.0          32880.0            32940.0
1            27440.0           27400.0          32290.0            31430.0
2            27440.0           27630.0          32290.0            32580.0
3            27440.0           27470.0          32340.0            32540.0
4            27440.0           27350.0          32310.0            32590.0
...              ...               ...              ...                ...
999          40740.0           40560.0          45260.0            45150.0
1000         38980.0           40560.0          44950.0            45530.0
1001         40660.0           40580.0          45190.0            45300.0
1002         40510.0           40380.0          43960.0            45600.0
1003         40510.0           40500.0          44640.0            46480.0

      Sulawesi Utara  Sumatera Barat  Sumatera Selatan  Sumatera Utara
0            35040.0         26700.0           26540.0         29250.0
1            34380.0         25970.0           26380.0         30420.0
2            33620.0         26030.0           26720.0         29900.0
3            32640.0         26060.0           26730.0         29400.0
4            33190.0         26030.0           25340.0         28970.0
...              ...             ...               ...             ...
999          43980.0         38610.0           37470.0         38180.0
1000         44850.0         38460.0           37450.0         38100.0
1001         44650.0         38310.0           37670.0         38320.0
1002         44070.0         38520.0           37370.0         38520.0
1003         44580.0         37300.0           37540.0         38340.0

[1004 rows x 35 columns]
            Date     Aceh     Bali   Banten  Bengkulu  DI Yogyakarta  \
0     2022-01-01  11030.0  10290.0   9960.0   10100.0         9650.0
1     2022-01-02  10950.0  10320.0   9800.0   10130.0         9650.0
2     2022-01-03  10970.0  10340.0  10040.0   10170.0         9610.0
3     2022-01-04  10990.0  10470.0   9900.0   10230.0         9610.0
4     2022-01-05  11050.0  10490.0   9750.0   10200.0         9470.0
...          ...      ...      ...      ...       ...            ...
999   2024-09-26  13470.0  14080.0  12600.0   13900.0        12980.0
1000  2024-09-27  13420.0  14080.0  12860.0   13900.0        13010.0
1001  2024-09-28  13510.0  14080.0  12700.0   13900.0        13010.0
1002  2024-09-29  13470.0  14080.0  12840.0   13900.0        13010.0
1003  2024-09-30  13470.0  14080.0  12800.0   13900.0        13010.0

      DKI Jakarta  Gorontalo    Jambi  Jawa Barat  ...    Papua     Riau  \
0         11270.0    10190.0   9990.0     10140.0  ...  12390.0  12560.0
1         11010.0    10120.0  10110.0     10160.0  ...  12950.0  12630.0
2         11010.0    10190.0  10080.0     10170.0  ...  12910.0  12490.0
3         11010.0    10260.0  10000.0     10180.0  ...  12910.0  12440.0
4         11010.0    10250.0  10080.0     10180.0  ...  12820.0  12610.0
...           ...        ...      ...         ...  ...      ...      ...
999       13600.0    13370.0  13120.0     12960.0  ...  15510.0  14090.0
1000      13950.0    13420.0  13120.0     12970.0  ...  15510.0  14110.0
1001      13690.0    13420.0  13130.0     12900.0  ...  15510.0  14040.0
1002      13690.0    13460.0  13130.0     12930.0  ...  15370.0  14070.0
1003      13420.0    13530.0  13190.0     12890.0  ...  15510.0  13930.0

      Sulawesi Barat  Sulawesi Selatan  Sulawesi Tengah  Sulawesi Tenggara  \
0             9880.0            9550.0          10070.0            10220.0
1             9980.0            9570.0           9940.0            10090.0
2             9810.0            9540.0          10180.0            10100.0
3             9810.0            9560.0          10270.0            10120.0
4             9810.0            9590.0          10230.0            10070.0
...              ...               ...              ...                ...
999          13220.0           12560.0          13440.0            13200.0
1000         13090.0           12610.0          13440.0            12970.0
1001         13100.0           12540.0          13440.0            13030.0
1002         13100.0           12520.0          13420.0            12950.0
1003         13200.0           12530.0          13440.0            13070.0

      Sulawesi Utara  Sumatera Barat  Sumatera Selatan  Sumatera Utara
0            10940.0         12250.0           10360.0         11290.0
1            10950.0         12210.0           10370.0         11400.0
2            10890.0         12100.0           10320.0         11360.0
3            10890.0         12120.0           10300.0         11300.0
4            10850.0         12090.0           10370.0         11200.0
...              ...             ...               ...             ...
999          13760.0         15240.0           12500.0         13970.0
1000         13760.0         15360.0           12540.0         13980.0
1001         13800.0         15260.0           12540.0         13960.0
1002         13730.0         15320.0           12540.0         13930.0
1003         13730.0         15280.0           12570.0         13950.0

[1004 rows x 35 columns]
            Date     Aceh     Bali   Banten  Bengkulu  DI Yogyakarta  \
0     2022-01-01  13520.0  12670.0  13240.0   13280.0        12590.0
1     2022-01-02  13540.0  12710.0  12920.0   13160.0        12590.0
2     2022-01-03  13430.0  12800.0  13080.0   13210.0        12590.0
3     2022-01-04  13580.0  12800.0  13180.0   13300.0        12590.0
4     2022-01-05  13460.0  12780.0  13060.0   13320.0        12870.0
...          ...      ...      ...      ...       ...            ...
999   2024-09-26  17990.0  17380.0  17280.0   17640.0        17080.0
1000  2024-09-27  17990.0  17380.0  17710.0   17640.0        17070.0
1001  2024-09-28  17990.0  17380.0  17510.0   17640.0        17070.0
1002  2024-09-29  17990.0  17380.0  17340.0   17640.0        17070.0
1003  2024-09-30  18030.0  17380.0  17950.0   17640.0        17000.0

      DKI Jakarta  Gorontalo    Jambi  Jawa Barat  ...    Papua     Riau  \
0         14480.0    13610.0  12950.0     13150.0  ...  14780.0  13030.0
1         14000.0    13440.0  13000.0     13210.0  ...  15490.0  12950.0
2         14320.0    13610.0  12950.0     13200.0  ...  15330.0  12990.0
3         14320.0    13500.0  12950.0     13230.0  ...  14630.0  13070.0
4         14320.0    13490.0  12950.0     13200.0  ...  15210.0  13170.0
...           ...        ...      ...         ...  ...      ...      ...
999       18240.0    17890.0  17450.0     17610.0  ...  19680.0  17510.0
1000      18560.0    18120.0  17450.0     17650.0  ...  19680.0  17400.0
1001      18320.0    18350.0  17450.0     17690.0  ...  19640.0  17470.0
1002      18080.0    18280.0  17450.0     17720.0  ...  19680.0  17540.0
1003      18410.0    18350.0  17310.0     17680.0  ...  19680.0  17510.0

      Sulawesi Barat  Sulawesi Selatan  Sulawesi Tengah  Sulawesi Tenggara  \
0            13780.0           13120.0          14170.0            14000.0
1            13640.0           13170.0          14020.0            13680.0
2            13550.0           13120.0          14160.0            13730.0
3            13640.0           13180.0          14430.0            13790.0
4            13640.0           13200.0          14430.0            13810.0
...              ...               ...              ...                ...
999          18210.0           17750.0          18640.0            18920.0
1000         18010.0           17750.0          18640.0            18990.0
1001         18210.0           17690.0          18640.0            18830.0